version: '3'

services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet
      MYSQL_PASSWORD: root
    ports:
      - 3308:3308
    volumes:
      - /home/felipe/develop/full_cycle/fc_wallet_core/docker/mysql:/var/lib/mysql