POST http://localhost:3000/clients HTTP/1.1
Content-type: application/json

{
  "name": "John Doe",
  "email": "j@j.com"
}

###

POST http://localhost:3000/accounts HTTP/1.1
Content-type: application/json

{
  "client_id": "7ab7dc72-214a-449d-80db-a276ff306a7b"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-type: application/json

{
  "account_id_from": "546e84c5-9408-4f0b-990b-3e0b09760348",
  "account_id_to": "783e7699-44a3-4da3-8092-a32e68402bc0",
  "amount": 70
}